services:
  api:
    build:
      target: testing
    container_name: rolelens_api_test
    environment:
      - DATABASE_URL=mongodb://localhost:27017/rolelens_test
      - TEST_DATABASE_URL=mongodb://localhost:27017/rolelens_test
      - ADZUNA_APP_ID=${ADZUNA_APP_ID:-test_id}
      - ADZUNA_APP_KEY=${ADZUNA_APP_KEY:-test_key}
    command: pytest -vv -ra --cov=app