services:
  api:
    build:
      target: development
    container_name: rolelens_api_dev
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://root:example@db:27017/rolelens_dev?authSource=admin
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo:7.0
    container_name: rolelens_mongo_dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: rolelens_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  mongo_dev_data: